name: Submit PR

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  submitPR:
    permissions: write-all
    name: Rebuild themes after theme submission
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup Python modules
        run: |
          pip3 install requests

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Rebuild all themes
        run: |
          python3 scripts/rebuild_themes.py

      - name: Commit changes
        run: |
          git add themes.json
          git add themes/*
          git commit -m "Rebuild themes.json after theme submission"
          git push
